C# Player's Guide - Swithces
LoganBSkinner/C-PlayersGuide pull request #7
Opened 2024-05-14 03:01 UTC by LoganBSkinner

- "Buying Inventory" and "Discounted Inventory" challenges.
- Accidentally included old files.

2024-05-15 03:39 UTC, LoganBSkinner commented
I don’t feel like I’m fully comfortable with some of the most basic interconnectedness of Visual Studio/GitHub. I understand some key pieces don’t quite know how the pieces fit together in specific scenarios. 

**Scenario #1**
I open up Visual Studio after a long break from work. The master branch has changes that aren’t on my IDE because my fellow developers have been hard at work during my absence. What do I do to sync up my computer with the master branch and make sure that my files are all the latest versions?

**My guess**
I need to pull those changes or click the sync button?

**Scenario #2**
I have made changes to a file that I have since tested locally and in dev. I now want to get those code reviewed.

**My guess**
Create a shelveset and assign a developer code review. Once approved, create a PR and assign a developer to approve. When that gets approved, push to the branch where it’s needed and notify the team.

**Scenario #3**
For the C# Player’s Guide, I’m aware that the specific project that I’m working on is a console app. All of the challenges that I’ve worked on thus far function independent of each other. Right now, they are saved individually as C# Class files. When I try to switch between those class files and debug them individually, I’m encountering build issues. How should I set myself up to test these individually?

**My guess**
I don’t really know.

2024-05-15 04:30 UTC, BenBolthouse commented
**Scenario #1**
I open up Visual Studio after a long break from work. The master branch has changes that aren’t on my IDE because my fellow developers have been hard at work during my absence. What do I do to sync up my computer with the master branch and make sure that my files are all the latest versions?

Here's a typical Git workflow for ensuring that you "get latest". I'll give you the CLI (command line interface) instructions, too.
1. Stash or commit any pending changes on your current branch (if any). `git add .` + `git commit -m "{message}"` or `git stash`
1. Checkout the master branch. `git checkout master`
1. Pull latest on your master branch. `git pull origin master`
1. Checkout the branch that you wish to update with the latest pulled commit history. `git checkout {branch-name}`
1. Merge the commit history on master into the current branch. `git merge master`.
I recommend doing this every time you start work after taking a break when, especially working in a team. Also do this when you know a dependent branch like master is undergoing a merge via pull request. Rule of thumb is to merge master into your branches as soon as possible. One last thing to note here is that if there isn't any history to merge in from the master branch, then it doesn't break anything. In other words, erring on merging master 'too often' is not a problem.

**Scenario #2**
I have made changes to a file that I have since tested locally and in dev. I now want to get those code reviewed.

First, be careful here to not confuse shelvesets with commits. 'Shelvesets' are a construct of Team Foundation Version Control, or TFVC, and 'commits' are a construct of Git. The two are different version control systems with some similarity. I know it's really confusing working at Shamrock where TFVC is used. Shelvesets and commits are functionally very different constructs of version control.
'Shelvesets' in TFVC are analogous to 'stashes' in Git, where 'changesets' in TFVC are analogous to 'commits' in Git.
That said, the typical Gitflow process is:
1. Commit changes in a local 'feature branch' (or sometimes called a 'source branch', i.e. any branch that you create with the intent to merge into a 'protected branch', like master. Sometimes this is called the 'target branch', especially in the context of a pull request).
1. Push the local branch to the remote. This creates the 'remote branch', in essence a remote copy of your local branch with the same branch name.
1. Make file local changes. Continue to commit those changes and push to the remote branch.
1. Once you are ready for a review, create the PR in Github to merge your feature branch (or 'source branch') to master. Add reviewers to your PR.
Note that while your PR is unfinished (and not yet merged), any pushes of new changes to your feature branch will be included in the pull request.

**Scenario #3**
For the C# Player’s Guide, I’m aware that the specific project that I’m working on is a console app. All of the challenges that I’ve worked on thus far function independent of each other. Right now, they are saved individually as C# Class files. When I try to switch between those class files and debug them individually, I’m encountering build issues. How should I set myself up to test these individually?

I'm looking into this. I'll get back to you.

2024-05-15 04:41 UTC, BenBolthouse requested changes
This all looks good. I would like to include the fix needed in point 3 of your questions regarding build problems before we complete the PR, and test that the fix works for your development. Let's get in touch on that point in particular in the next few days.

2024-05-15 04:41 UTC, BenBolthouse commented on BuyingInventory.cs
> +while (exit = !false)
* Inverse of `false` is `true`. Simplify this condition to be while `(exit == true)`.
* The `=` operator here is an assignment operator. Use `==` equality operator to build your looping condition.

2024-05-15 04:41 UTC, BenBolthouse commented on BuyingInventory.cs
> +            cost = 10;
* Assignment of `cost` here assigns cost in the global scope. This can have unintended side effects. Unless your tutorial explicitly requests that you reassign `cost` in the enclosing global scope, consider printing your item cost directly in the console without reassigning `cost`. I can explain this next time we get together.

2024-05-15 04:41 UTC, BenBolthouse commented on DiscountedInventory.cs
> +}
* The code smell here is that this `while` loop looks almost the same as the one below. This could be an opportunity to merge the two and rework the looping conditions and on-the-fly cost calculations based on role/group (i.e. you could could consider "Logan" a member of the "half off" role or group).

2024-05-15 04:41 UTC, BenBolthouse commented on DiscountedInventory.cs
> +while (exit == !false && halfOff == !false)
* The way that I read this is that while `exit == !false` (or essentially `exit == true`) is the first part of a two part looping condition connected by _AND_. At some point the loop must break based on reassignment of an enclosing scope variable. In this case, it would require assignment `exit = false`. Reading the input value "8" from the console, as read on line 56 and handled starting on line 97 _should_ terminate the loop. However, case "8" assigns `exit = true`, which shouldn't exit the loop on the next iteration. This may result in unexpected behavior of continued looping (and console prompting) as opposed to the expected behavior of termination of the loop and the program.

2024-05-15 04:41 UTC, BenBolthouse commented on DiscountedInventory.cs
> +while (exit == !false && halfOff == !false)
* Also, in case the book doesn't call this out, and because you are working on looping conditions and logical expressions, look into the concept of 'short circuiting'. If you need help understanding this, we can go over it in our next meetup.

2024-05-15 04:41 UTC, BenBolthouse commented on DiscountedInventory.cs
> +if (name == "Logan") // Use '==' for comparison, not '='
* Fun fact about equality operators:
  There is a difference between equality by _type_ and equality by _value_.
  Here you have a _string_ type being compared to another _string_ type. The left side of the operation is a string variable and the right side of the operation is a string literal.
  The left and right side also equal by value, _under certain conditions_. Here you handle for a specific condition: if `name` was previously assigned the value `"Logan"`. In that specific case, the values are equal.
  In other programming languages, you have different equality operators to assert type equality vs. value equality. For instance, in Typescript (and Javascript) the `==` operator checks for value equality while the `===` operator checks for type _and_ value equality. In C#, you get one equality operator that checks both type and value, which is the `==` operator.
  There are other means of checking for only type equality in C#. For instance, the `typeof(...)` operator does this for you. But that's likely a lesson for another time.

2024-05-19 22:51 UTC, BenBolthouse commented on DiscountedInventory.cs
> +if (name == "Logan") // Use '==' for comparison, not '='
Hey, thanks for looking at this. I will be sure to keep an eye out for that in the future, and I will correct this in a future pull request.

2024-05-19 22:51 UTC, BenBolthouse commented on DiscountedInventory.cs
> +while (exit == !false && halfOff == !false)
Hey, thanks for looking at this. I will be sure to keep an eye out for that in the future, and I will correct this in a future pull request.

2024-05-19 22:52 UTC, BenBolthouse commented on BuyingInventory.cs
> +            cost = 10;
Hey, thanks for looking at this. I will be sure to keep an eye out for that in the future, and I will correct this in a future pull request.

2024-05-19 22:53 UTC, BenBolthouse approved these changes
Good job resolving these, and thank you. Looks good, go ahead and merge!

2024-05-19 22:54 UTC, merged